# Generated by Django 3.2.10 on 2021-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_shopadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadmin',
            name='admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='ShopAdmin',
        ),
    ]
