# Generated by Django 3.2.10 on 2021-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211226_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'Admin'), (3, 'Customer')], default=1, max_length=10),
        ),
    ]
