# Generated by Django 3.2.10 on 2021-12-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=60, verbose_name='Category Slug')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Medicine Title')),
                ('slug', models.SlugField(max_length=100, verbose_name='Medicine Slug')),
                ('image', models.ImageField(upload_to='medicines', verbose_name='Medicine Image')),
                ('manufactured_by', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(verbose_name='Is Active?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.category')),
            ],
        ),
    ]
