# Generated by Django 3.2.10 on 2021-12-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, upload_to='medicines', verbose_name='Medicine Image'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufactured_by',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
