# Generated by Django 3.2.10 on 2021-12-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_admin_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
