# Generated by Django 3.2.10 on 2022-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20211225_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
