# Generated by Django 3.2.10 on 2022-01-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_medicine_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
