# Generated by Django 3.2.10 on 2022-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_alter_medicine_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
