# Generated by Django 3.2.10 on 2022-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0010_alter_medicine_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
